<?php

namespace App\Filament\Accounting\Resources\JurnalMemorialResource\Pages;

use App\Filament\Accounting\Resources\JurnalMemorialResource;
use App\Models\JurnalMemorial;
use App\Models\Rekening;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Str;
use Livewire\Attributes\On;

class CreateJurnalMemorial extends CreateRecord
{
    protected static string $resource = JurnalMemorialResource::class;

    #[On('remove-memorial-item')]
    public function removeMemorialItem($index)
    {
        $data = $this->form->getState();
        $items = $data['detail_rekening'] ?? [];

        if (isset($items[$index])) {
            unset($items[$index]);
            $items = array_values($items); // Reindex array
            $this->form->fill(['detail_rekening' => $items]);
        }
    }

    protected function handleRecordCreation(array $data): JurnalMemorial
    {
        // Extract items from detail_rekening
        $items = $data['detail_rekening'] ?? [];
        unset($data['detail_rekening']);
        unset($data['items_completed']);
        unset($data['temp_rekening']);
        unset($data['temp_nomor_bantu']);
        unset($data['temp_kode_proyek']);
        unset($data['temp_position']);
        unset($data['temp_jumlah']);
        unset($data['temp_keterangan']);

        if (empty($items)) {
            throw new \Exception('Minimal harus ada 1 item memorial');
        }

        // Hitung total debit dan kredit
        $totalDebit = collect($items)->where('position', 'debit')->sum('jumlah');
        $totalKredit = collect($items)->where('position', 'kredit')->sum('jumlah');

        // Validasi balance
        if ($totalDebit != $totalKredit) {
            throw new \Exception('Total Debit (Rp ' . number_format($totalDebit, 0, ',', '.') . ') harus sama dengan Total Kredit (Rp ' . number_format($totalKredit, 0, ',', '.') . ')');
        }

        // Generate no_bukti sekali
        $bukti = $data['bukti'] ?? 'MEM-' . rand(100, 999);

        // Prepare header data
        $headerData = [
            'no_reff' => $data['no_reff'] ?? null, // Will be auto-generated by model boot
            'tanggal' => $data['tanggal'],
            'bukti' => $bukti,
            'rp' => $totalDebit, // Total transaksi
            'keterangan' => 'Jurnal Memorial - ' . count($items) . ' item(s)',
            'company_id' => $data['company_id'] ?? 1,
            'created_by' => auth()->id(),
            'is_confirmed' => false,
        ];

        // Create header record
        $header = JurnalMemorial::create($headerData);

        // Create detail records
        foreach ($items as $item) {
            $rekening = null;
            if (!empty($item['rekening'])) {
                $rekening = Rekening::with('kelompok')->find($item['rekening']);
            }

            $position = $item['position'] ?? 'debit';
            $jumlah = (float) ($item['jumlah'] ?? 0);

            \App\Models\JurnalMemorialDetail::create([
                'jurnal_memorial_id' => $header->id,
                'bukti' => $bukti,
                'keterangan' => $item['keterangan'] ?? '',
                'jumlah' => $jumlah,
                'posisi' => $position === 'debit' ? 'D' : 'K',
                'kelompok_id' => $rekening?->kelompok_id,
                'rekening_id' => $item['rekening'] ?? null,
                'nomor_bantu_id' => $item['nomor_bantu'] ?? null,
                'kode_proyek_id' => $item['kode_proyek'] ?? null,
            ]);
        }

        return $header;
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
