<?php

namespace App\Filament\Accounting\Resources\JurnalPemakaianBahanResource\Pages;

use App\Filament\Accounting\Resources\JurnalPemakaianBahanResource;
use App\Models\JurnalPemakaianBahan;
use App\Models\Rekening;
use Filament\Resources\Pages\CreateRecord;

class CreateJurnalPemakaianBahan extends CreateRecord
{
    protected static string $resource = JurnalPemakaianBahanResource::class;

    public function removeItem($index)
    {
        try {
            $items = $this->data['detail_rekening'] ?? [];

            if (isset($items[$index])) {
                array_splice($items, $index, 1);
                $this->data['detail_rekening'] = $items;

                \Filament\Notifications\Notification::make()
                    ->title('Item berhasil dihapus!')
                    ->success()
                    ->send();
            }
        } catch (\Exception $e) {
            \Filament\Notifications\Notification::make()
                ->title('Gagal menghapus item')
                ->body($e->getMessage())
                ->danger()
                ->send();
        }
    }

    public function editItem($index)
    {
        try {
            $items = $this->data['detail_rekening'] ?? [];

            if (!isset($items[$index])) {
                return;
            }

            $item = $items[$index];
            $this->data['temp_rekening'] = $item['rekening'] ?? $item['rekening_id'] ?? null;
            $this->data['temp_nomor_bantu'] = $item['nomor_bantu'] ?? $item['nomor_bantu_id'] ?? null;
            $this->data['temp_kode_proyek'] = $item['kode_proyek'] ?? $item['kode_proyek_id'] ?? null;
            $this->data['temp_position'] = $item['position'] ?? 'debit';
            $this->data['temp_jumlah'] = number_format((float) ($item['jumlah'] ?? 0), 0, ',', '.');
            $this->data['temp_keterangan'] = $item['keterangan'] ?? null;

            array_splice($items, $index, 1);
            $this->data['detail_rekening'] = $items;

            \Filament\Notifications\Notification::make()
                ->title('Item dimuat untuk diedit')
                ->info()
                ->send();
        } catch (\Exception $e) {
            \Filament\Notifications\Notification::make()
                ->title('Gagal memuat item')
                ->body($e->getMessage())
                ->danger()
                ->send();
        }
    }

    protected function handleRecordCreation(array $data): JurnalPemakaianBahan
    {
        // Extract items from detail_rekening
        $items = $data['detail_rekening'] ?? [];
        unset($data['detail_rekening']);
        unset($data['items_completed']);
        unset($data['temp_rekening']);
        unset($data['temp_nomor_bantu']);
        unset($data['temp_kode_proyek']);
        unset($data['temp_position']);
        unset($data['temp_jumlah']);
        unset($data['temp_keterangan']);

        if (empty($items)) {
            throw new \Exception('Minimal harus ada 1 item pemakaian bahan');
        }

        // Hitung total debit dan kredit
        $totalDebit = collect($items)->where('position', 'debit')->sum('jumlah');
        $totalKredit = collect($items)->where('position', 'kredit')->sum('jumlah');

        // Validasi balance
        if ($totalDebit != $totalKredit) {
            throw new \Exception('Total Debit (Rp ' . number_format($totalDebit, 0, ',', '.') . ') harus sama dengan Total Kredit (Rp ' . number_format($totalKredit, 0, ',', '.') . ')');
        }

        // Generate no_bukti sekali
        $bukti = $data['bukti'] ?? 'JPBIK-' . rand(100, 999);

        // Prepare header data
        $headerData = [
            'no_reff' => $data['no_reff'] ?? null, // Will be auto-generated by model boot
            'tanggal' => $data['tanggal'],
            'bukti' => $bukti,
            'rp' => $totalDebit, // Total transaksi
            'keterangan' => 'Jurnal Pemakaian Bahan - ' . count($items) . ' item(s)',
            'company_id' => $data['company_id'] ?? 1,
            'created_by' => auth()->id(),
            'is_confirmed' => false,
        ];

        // Create header record
        $header = JurnalPemakaianBahan::create($headerData);

        // Create detail records
        $createdDetails = [];
        foreach ($items as $item) {
            $rekening = null;
            if (!empty($item['rekening'])) {
                $rekening = Rekening::with('kelompok')->find($item['rekening']);
            }

            $position = $item['position'] ?? 'debit';
            $jumlah = (float) ($item['jumlah'] ?? 0);

            // Tentukan debit/kredit berdasarkan position
            $detailData = [
                'jurnal_pemakaian_bahan_id' => $header->id,
                'bukti' => $bukti,
                'keterangan' => $item['keterangan'] ?? '',
                'jumlah' => $jumlah,
                'beban_bagian' => $item['beban_bagian'] ?? null,
                'kode_proyek_id' => $item['kode_proyek'] ?? null,
            ];

            if ($position === 'debit') {
                $detailData['kelompok_debit_id'] = $rekening?->kelompok_id;
                $detailData['rekening_debit_id'] = $item['rekening'] ?? null;
                $detailData['nomor_bantu_debit_id'] = $item['nomor_bantu'] ?? null;
            } else {
                $detailData['kelompok_kredit_id'] = $rekening?->kelompok_id;
                $detailData['rekening_kredit_id'] = $item['rekening'] ?? null;
                $detailData['nomor_bantu_kredit_id'] = $item['nomor_bantu'] ?? null;
            }

            $createdDetails[] = \App\Models\JurnalPemakaianBahanDetail::create($detailData);
        }

        return $createdDetails[0];
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
